.TH man 1 "2019-08-11" "wordlisto"
.SH NAME
Wordlisto \- a custom wordlists generator tool
.SH SYNTAX
 ./wordlisto [-s -c -t -w -a -l --custom] || --help
.SH DESCRIPTION
	Wordilisto is a tool wrote in C language, has objetive of generate wordlist with a known target
.SH OPTIONS
.B 	The arguments are used to complement the user enters with an additional affair
.IP -s <simple>
	This argument use a empty wordlist, so the wordlist ll be generate without none subject.
.IP -c <commom> 
	This argument use some popular words in personal passwords.
.IP -m <music>
	Use this to add some words about the music world, like singers, bands and music names.
.IP -t <tech>
	This argument add words about computers, systems and famous TI people
.IP -w <shows>
	You can use it if the Target like tv shows, and movies
.IP -a <anime>
	This argument ll add some cartoons and anime in your wordlist
.IP -l <all>
	If you want add all the previous arguments, use only this.
.IP --custom
	You can add your own wordlist to the tool, but be careful, if the wordlist is so big, the program can crash.
.SH AUTHOR
	by Calistu, in 2019-08-10
